version: "1.0"

services:
  person-api:
    build: .
    ports:
      - "1234:1234"
    depends_on:
      - db
    environment:
      - PORT=":1234"
      - USEMOCK="false"
  
  db:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: person